/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dicegame;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class DiceGameTest {
    @ParameterizedTest
    @MethodSource("provideDicValues")
    void play_a_DiceGame(int roll1, int roll2, boolean isWinner) {
        
        Die die1 = new Die(roll1);
        Die die2 = new Die(roll2);

        DiceGame game = new DiceGame(die1, die2, 7);
        game.play();

        assertEquals(isWinner, game.isWon());
    }

    static Stream<Arguments> provideDicValues() {
        return Stream.of(
                Arguments.of(1, 1, false),
                Arguments.of(1, 2, false),
                Arguments.of(2, 1, false),
                Arguments.of(5, 2, true)
        );
    }
}
